import type { ModelSpec } from "./types";

export const MODELS: ModelSpec[] = [
  {
    id: "llama3.2-1b",
    name: "Llama 3.2 1B",
    org: "Meta",
    family: "Llama",
    paramsB: 1.24,
    architecture: "dense",
    contextK: 128,
    license: "Llama 3.2 Community",
    commercial: true,
    released: "2024-09",
    tasks: ["chat", "lightweight"],
    description: "Tiny on-device Llama — edge chat, classification, and rewriting on phones and iGPUs.",
    features: { tools: true },
    ollama: "llama3.2:1b",
    huggingface: "meta-llama/Llama-3.2-1B-Instruct",
    popularity: 88,
  },
  {
    id: "llama3.2-3b",
    name: "Llama 3.2 3B",
    org: "Meta",
    family: "Llama",
    paramsB: 3.21,
    architecture: "dense",
    contextK: 128,
    license: "Llama 3.2 Community",
    commercial: true,
    released: "2024-09",
    tasks: ["chat", "lightweight", "code"],
    description: "The sweet-spot tiny Llama. Strong instruction following for its size, great laptop default.",
    features: { tools: true, coding: true },
    ollama: "llama3.2:3b",
    huggingface: "meta-llama/Llama-3.2-3B-Instruct",
    popularity: 94,
  },
  {
    id: "llama3.1-8b",
    name: "Llama 3.1 8B",
    org: "Meta",
    family: "Llama",
    paramsB: 8.03,
    architecture: "dense",
    contextK: 128,
    license: "Llama 3.1 Community",
    commercial: true,
    released: "2024-07",
    tasks: ["chat", "code"],
    description: "The workhorse 8B. Tool use, 128K context, and a huge GGUF ecosystem.",
    features: { tools: true, coding: true },
    ollama: "llama3.1:8b",
    huggingface: "meta-llama/Llama-3.1-8B-Instruct",
    popularity: 99,
  },
  {
    id: "llama3.1-70b",
    name: "Llama 3.1 70B",
    org: "Meta",
    family: "Llama",
    paramsB: 70.6,
    architecture: "dense",
    contextK: 128,
    license: "Llama 3.1 Community",
    commercial: true,
    released: "2024-07",
    tasks: ["chat", "code", "reasoning"],
    description: "Frontier-class dense 70B. Needs a 24GB+ card at Q4, or unified memory on Apple.",
    features: { tools: true, coding: true },
    ollama: "llama3.1:70b",
    huggingface: "meta-llama/Llama-3.1-70B-Instruct",
    popularity: 91,
  },
  {
    id: "llama3.3-70b",
    name: "Llama 3.3 70B",
    org: "Meta",
    family: "Llama",
    paramsB: 70.6,
    architecture: "dense",
    contextK: 128,
    license: "Llama 3.3 Community",
    commercial: true,
    released: "2024-12",
    tasks: ["chat", "code", "reasoning"],
    description: "Drop-in upgrade over 3.1 70B — better multilingual and instruction quality at the same size.",
    features: { tools: true, coding: true },
    ollama: "llama3.3:70b",
    huggingface: "meta-llama/Llama-3.3-70B-Instruct",
    popularity: 93,
  },
  {
    id: "llama3.2-11b-vision",
    name: "Llama 3.2 11B Vision",
    org: "Meta",
    family: "Llama",
    paramsB: 10.6,
    architecture: "dense",
    contextK: 128,
    license: "Llama 3.2 Community",
    commercial: true,
    released: "2024-09",
    tasks: ["chat", "vision"],
    description: "Multimodal Llama that reads images, charts, and screenshots locally.",
    features: { tools: true, vision: true },
    ollama: "llama3.2-vision:11b",
    huggingface: "meta-llama/Llama-3.2-11B-Vision-Instruct",
    popularity: 82,
  },
  {
    id: "llama4-scout",
    name: "Llama 4 Scout",
    org: "Meta",
    family: "Llama",
    paramsB: 109,
    activeParamsB: 17,
    architecture: "moe",
    contextK: 10000,
    license: "Llama 4 Community",
    commercial: true,
    released: "2025-04",
    tasks: ["chat", "code", "vision", "reasoning"],
    description: "Mixture-of-experts Llama 4 with a 10M context window and native multimodality.",
    features: { tools: true, vision: true, coding: true },
    ollama: "llama4:scout",
    huggingface: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    popularity: 90,
  },
  {
    id: "qwen2.5-3b",
    name: "Qwen 2.5 3B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 3.09,
    architecture: "dense",
    contextK: 32,
    license: "Apache 2.0",
    commercial: true,
    released: "2024-09",
    tasks: ["chat", "code", "lightweight"],
    description: "Apache-licensed 3B that punches above its weight on coding and multilingual chat.",
    features: { tools: true, coding: true },
    ollama: "qwen2.5:3b",
    huggingface: "Qwen/Qwen2.5-3B-Instruct",
    popularity: 86,
  },
  {
    id: "qwen2.5-7b",
    name: "Qwen 2.5 7B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 7.61,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2024-09",
    tasks: ["chat", "code"],
    description: "Best all-rounder under 8B for many laptops. Strong coder, 128K context, Apache 2.0.",
    features: { tools: true, coding: true },
    ollama: "qwen2.5:7b",
    huggingface: "Qwen/Qwen2.5-7B-Instruct",
    popularity: 97,
  },
  {
    id: "qwen2.5-14b",
    name: "Qwen 2.5 14B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 14.7,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2024-09",
    tasks: ["chat", "code", "reasoning"],
    description: "The 14B that fits a 12GB card at Q4 and feels closer to 32B on many tasks.",
    features: { tools: true, coding: true },
    ollama: "qwen2.5:14b",
    huggingface: "Qwen/Qwen2.5-14B-Instruct",
    popularity: 89,
  },
  {
    id: "qwen2.5-32b",
    name: "Qwen 2.5 32B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 32.8,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2024-09",
    tasks: ["chat", "code", "reasoning"],
    description: "Dense 32B for 24GB cards. Excellent coding and agentic tool use.",
    features: { tools: true, coding: true },
    ollama: "qwen2.5:32b",
    huggingface: "Qwen/Qwen2.5-32B-Instruct",
    popularity: 87,
  },
  {
    id: "qwen2.5-72b",
    name: "Qwen 2.5 72B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 72.7,
    architecture: "dense",
    contextK: 128,
    license: "Qwen",
    commercial: true,
    released: "2024-09",
    tasks: ["chat", "code", "reasoning"],
    description: "Flagship dense Qwen 2.5. Needs 48GB or unified memory to be pleasant.",
    features: { tools: true, coding: true },
    ollama: "qwen2.5:72b",
    huggingface: "Qwen/Qwen2.5-72B-Instruct",
    popularity: 84,
  },
  {
    id: "qwen2.5-coder-7b",
    name: "Qwen 2.5 Coder 7B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 7.61,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2024-11",
    tasks: ["code", "chat"],
    description: "Specialist coder 7B. FIM, repo-level edits, and strong fill-in-the-middle.",
    features: { tools: true, coding: true },
    ollama: "qwen2.5-coder:7b",
    huggingface: "Qwen/Qwen2.5-Coder-7B-Instruct",
    popularity: 95,
  },
  {
    id: "qwen2.5-coder-32b",
    name: "Qwen 2.5 Coder 32B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 32.5,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2024-11",
    tasks: ["code", "chat"],
    description: "One of the strongest local coding models. Pair with a repo connection.",
    features: { tools: true, coding: true },
    ollama: "qwen2.5-coder:32b",
    huggingface: "Qwen/Qwen2.5-Coder-32B-Instruct",
    popularity: 92,
  },
  {
    id: "qwen3-8b",
    name: "Qwen 3 8B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 8.2,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2025-04",
    tasks: ["chat", "code", "reasoning"],
    description: "Hybrid thinking model — toggle deeper chain-of-thought without a bigger card.",
    features: { tools: true, thinking: true, coding: true },
    ollama: "qwen3:8b",
    huggingface: "Qwen/Qwen3-8B",
    popularity: 96,
  },
  {
    id: "qwen3-14b",
    name: "Qwen 3 14B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 14.8,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2025-04",
    tasks: ["chat", "code", "reasoning"],
    description: "Thinking-capable 14B. The 12GB-card reasoning pick for 2025.",
    features: { tools: true, thinking: true, coding: true },
    ollama: "qwen3:14b",
    huggingface: "Qwen/Qwen3-14B",
    popularity: 91,
  },
  {
    id: "qwen3-32b",
    name: "Qwen 3 32B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 32.8,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2025-04",
    tasks: ["chat", "code", "reasoning"],
    description: "Dense thinking 32B. Excellent agents when it fits in VRAM.",
    features: { tools: true, thinking: true, coding: true },
    ollama: "qwen3:32b",
    huggingface: "Qwen/Qwen3-32B",
    popularity: 88,
  },
  {
    id: "qwen3-30b-a3b",
    name: "Qwen 3 30B-A3B",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 30.5,
    activeParamsB: 3.3,
    architecture: "moe",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2025-04",
    tasks: ["chat", "code", "reasoning", "lightweight"],
    description: "MoE with 3.3B active params — 30B quality at roughly 7B speed.",
    features: { tools: true, thinking: true, coding: true },
    ollama: "qwen3:30b-a3b",
    huggingface: "Qwen/Qwen3-30B-A3B",
    popularity: 90,
  },
  {
    id: "gemma3-1b",
    name: "Gemma 3 1B",
    org: "Google",
    family: "Gemma",
    paramsB: 1.0,
    architecture: "dense",
    contextK: 32,
    license: "Gemma",
    commercial: true,
    released: "2025-03",
    tasks: ["chat", "lightweight"],
    description: "On-device Gemma. Fast, polite, and small enough for any machine.",
    features: {},
    ollama: "gemma3:1b",
    huggingface: "google/gemma-3-1b-it",
    popularity: 80,
  },
  {
    id: "gemma3-4b",
    name: "Gemma 3 4B",
    org: "Google",
    family: "Gemma",
    paramsB: 4.3,
    architecture: "dense",
    contextK: 128,
    license: "Gemma",
    commercial: true,
    released: "2025-03",
    tasks: ["chat", "vision", "lightweight"],
    description: "Multimodal 4B with 128K context. The new default tiny vision model.",
    features: { vision: true },
    ollama: "gemma3:4b",
    huggingface: "google/gemma-3-4b-it",
    popularity: 92,
  },
  {
    id: "gemma3-12b",
    name: "Gemma 3 12B",
    org: "Google",
    family: "Gemma",
    paramsB: 12.2,
    architecture: "dense",
    contextK: 128,
    license: "Gemma",
    commercial: true,
    released: "2025-03",
    tasks: ["chat", "vision", "code"],
    description: "12B multimodal Gemma. Fits 8–12GB at Q4 with room for a long context.",
    features: { vision: true, coding: true },
    ollama: "gemma3:12b",
    huggingface: "google/gemma-3-12b-it",
    popularity: 88,
  },
  {
    id: "gemma3-27b",
    name: "Gemma 3 27B",
    org: "Google",
    family: "Gemma",
    paramsB: 27.4,
    architecture: "dense",
    contextK: 128,
    license: "Gemma",
    commercial: true,
    released: "2025-03",
    tasks: ["chat", "vision", "code", "reasoning"],
    description: "Flagship open Gemma. Needs ~16GB at Q4, 24GB to breathe.",
    features: { vision: true, coding: true },
    ollama: "gemma3:27b",
    huggingface: "google/gemma-3-27b-it",
    popularity: 85,
  },
  {
    id: "phi4-14b",
    name: "Phi-4 14B",
    org: "Microsoft",
    family: "Phi",
    paramsB: 14.7,
    architecture: "dense",
    contextK: 16,
    license: "MIT",
    commercial: true,
    released: "2024-12",
    tasks: ["chat", "code", "reasoning"],
    description: "Data-efficient 14B. Remarkable math and coding for the parameter count.",
    features: { coding: true },
    ollama: "phi4",
    huggingface: "microsoft/phi-4",
    popularity: 86,
  },
  {
    id: "phi4-mini",
    name: "Phi-4 Mini 3.8B",
    org: "Microsoft",
    family: "Phi",
    paramsB: 3.8,
    architecture: "dense",
    contextK: 128,
    license: "MIT",
    commercial: true,
    released: "2025-02",
    tasks: ["chat", "code", "lightweight"],
    description: "MIT-licensed mini Phi with 128K context and function calling.",
    features: { tools: true, coding: true },
    ollama: "phi4-mini",
    huggingface: "microsoft/Phi-4-mini-instruct",
    popularity: 84,
  },
  {
    id: "mistral-nemo",
    name: "Mistral Nemo 12B",
    org: "Mistral AI",
    family: "Mistral",
    paramsB: 12.2,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2024-07",
    tasks: ["chat", "code"],
    description: "Apache 12B with 128K context. A classic local daily driver.",
    features: { tools: true, coding: true },
    ollama: "mistral-nemo",
    huggingface: "mistralai/Mistral-Nemo-Instruct-2407",
    popularity: 83,
  },
  {
    id: "mistral-small-3.1",
    name: "Mistral Small 3.1 24B",
    org: "Mistral AI",
    family: "Mistral",
    paramsB: 24,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2025-03",
    tasks: ["chat", "code", "vision", "reasoning"],
    description: "Multimodal 24B Apache model. The 24GB-card Mistral pick.",
    features: { tools: true, vision: true, coding: true },
    ollama: "mistral-small3.1",
    huggingface: "mistralai/Mistral-Small-3.1-24B-Instruct-2503",
    popularity: 87,
  },
  {
    id: "mixtral-8x7b",
    name: "Mixtral 8x7B",
    org: "Mistral AI",
    family: "Mistral",
    paramsB: 46.7,
    activeParamsB: 12.9,
    architecture: "moe",
    contextK: 32,
    license: "Apache 2.0",
    commercial: true,
    released: "2023-12",
    tasks: ["chat", "code"],
    description: "The original open MoE. 47B on disk, ~13B active — still a great 16–24GB model.",
    features: { coding: true },
    ollama: "mixtral:8x7b",
    huggingface: "mistralai/Mixtral-8x7B-Instruct-v0.1",
    popularity: 78,
  },
  {
    id: "codestral-22b",
    name: "Codestral 22B",
    org: "Mistral AI",
    family: "Mistral",
    paramsB: 22.2,
    architecture: "dense",
    contextK: 32,
    license: "MRL",
    commercial: true,
    released: "2024-05",
    tasks: ["code"],
    description: "Fill-in-the-middle coding specialist. Pair with a VS project for repo edits.",
    features: { coding: true },
    ollama: "codestral",
    huggingface: "mistralai/Codestral-22B-v0.1",
    popularity: 79,
  },
  {
    id: "deepseek-r1-distill-8b",
    name: "DeepSeek R1 Distill 8B",
    org: "DeepSeek",
    family: "DeepSeek",
    paramsB: 8.03,
    architecture: "dense",
    contextK: 128,
    license: "MIT",
    commercial: true,
    released: "2025-01",
    tasks: ["reasoning", "chat", "code"],
    description: "R1 reasoning distilled into Llama 8B. Thinks out loud, fits any 8GB card.",
    features: { thinking: true, coding: true },
    ollama: "deepseek-r1:8b",
    huggingface: "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
    popularity: 94,
  },
  {
    id: "deepseek-r1-distill-14b",
    name: "DeepSeek R1 Distill 14B",
    org: "DeepSeek",
    family: "DeepSeek",
    paramsB: 14.8,
    architecture: "dense",
    contextK: 128,
    license: "MIT",
    commercial: true,
    released: "2025-01",
    tasks: ["reasoning", "chat", "code"],
    description: "Qwen-based R1 distill. The 12GB reasoning sweet spot.",
    features: { thinking: true, coding: true },
    ollama: "deepseek-r1:14b",
    huggingface: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    popularity: 90,
  },
  {
    id: "deepseek-r1-distill-32b",
    name: "DeepSeek R1 Distill 32B",
    org: "DeepSeek",
    family: "DeepSeek",
    paramsB: 32.8,
    architecture: "dense",
    contextK: 128,
    license: "MIT",
    commercial: true,
    released: "2025-01",
    tasks: ["reasoning", "chat", "code"],
    description: "32B R1 distill. Near-full R1 math on a 24GB card at Q4.",
    features: { thinking: true, coding: true },
    ollama: "deepseek-r1:32b",
    huggingface: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
    popularity: 88,
  },
  {
    id: "deepseek-r1-70b",
    name: "DeepSeek R1 Distill 70B",
    org: "DeepSeek",
    family: "DeepSeek",
    paramsB: 70.6,
    architecture: "dense",
    contextK: 128,
    license: "MIT",
    commercial: true,
    released: "2025-01",
    tasks: ["reasoning", "chat", "code"],
    description: "Llama 70B distilled from R1. Heavy, brilliant, MIT-licensed.",
    features: { thinking: true, coding: true },
    ollama: "deepseek-r1:70b",
    huggingface: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
    popularity: 82,
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    org: "DeepSeek",
    family: "DeepSeek",
    paramsB: 671,
    activeParamsB: 37,
    architecture: "moe",
    contextK: 128,
    license: "MIT",
    commercial: true,
    released: "2024-12",
    tasks: ["chat", "code", "reasoning"],
    description: "671B MoE with 37B active. Datacenter-class; Q2 still wants 200GB+.",
    features: { tools: true, coding: true },
    ollama: "deepseek-v3",
    huggingface: "deepseek-ai/DeepSeek-V3",
    popularity: 80,
  },
  {
    id: "gpt-oss-20b",
    name: "GPT-OSS 20B",
    org: "OpenAI",
    family: "GPT-OSS",
    paramsB: 21,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2025-08",
    tasks: ["chat", "code", "reasoning"],
    description: "OpenAI's open-weight 20B. Strong generalist for 16GB cards.",
    features: { tools: true, coding: true },
    ollama: "gpt-oss:20b",
    huggingface: "openai/gpt-oss-20b",
    popularity: 89,
  },
  {
    id: "gpt-oss-120b",
    name: "GPT-OSS 120B",
    org: "OpenAI",
    family: "GPT-OSS",
    paramsB: 117,
    architecture: "dense",
    contextK: 128,
    license: "Apache 2.0",
    commercial: true,
    released: "2025-08",
    tasks: ["chat", "code", "reasoning"],
    description: "OpenAI 120B open weights. Needs 48GB+ or serious unified memory.",
    features: { tools: true, coding: true },
    ollama: "gpt-oss:120b",
    huggingface: "openai/gpt-oss-120b",
    popularity: 81,
  },
  {
    id: "glm4-9b",
    name: "GLM-4 9B",
    org: "Zhipu AI",
    family: "GLM",
    paramsB: 9.4,
    architecture: "dense",
    contextK: 128,
    license: "GLM-4",
    commercial: true,
    released: "2024-10",
    tasks: ["chat", "code"],
    description: "Agent-native 9B with strong tool use and bilingual quality.",
    features: { tools: true, coding: true },
    ollama: "glm4:9b",
    huggingface: "THUDM/glm-4-9b-chat",
    popularity: 76,
  },
  {
    id: "command-r-35b",
    name: "Command R 35B",
    org: "Cohere",
    family: "Command",
    paramsB: 35,
    architecture: "dense",
    contextK: 128,
    license: "CC-BY-NC-4.0",
    commercial: false,
    released: "2024-03",
    tasks: ["chat", "reasoning"],
    description: "RAG-first 35B with citations. Non-commercial weights.",
    features: { tools: true },
    ollama: "command-r",
    huggingface: "CohereForAI/c4ai-command-r-v01",
    popularity: 70,
  },
  {
    id: "nomic-embed-text",
    name: "Nomic Embed Text",
    org: "Nomic",
    family: "Embed",
    paramsB: 0.14,
    architecture: "dense",
    contextK: 8,
    license: "Apache 2.0",
    commercial: true,
    released: "2024-02",
    tasks: ["embed", "lightweight"],
    description: "Local embedding model for project search and RAG over your repos.",
    features: {},
    ollama: "nomic-embed-text",
    huggingface: "nomic-ai/nomic-embed-text-v1.5",
    popularity: 77,
  },
  {
    id: "flux-schnell",
    name: "FLUX.1 Schnell",
    org: "Black Forest Labs",
    family: "FLUX",
    paramsB: 12,
    architecture: "dense",
    contextK: 0.5,
    license: "Apache 2.0",
    commercial: true,
    released: "2024-08",
    tasks: ["image"],
    description: "4-step distilled text-to-image. Apache 2.0, runs on 8–12GB.",
    features: {},
    ollama: undefined,
    huggingface: "black-forest-labs/FLUX.1-schnell",
    popularity: 85,
  },
  {
    id: "flux2-klein-4b",
    name: "FLUX.2 Klein 4B",
    org: "Black Forest Labs",
    family: "FLUX",
    paramsB: 4,
    architecture: "dense",
    contextK: 32,
    license: "Apache 2.0",
    commercial: true,
    released: "2026-01",
    tasks: ["image", "lightweight"],
    description: "Fastest open FLUX.2 — sub-second text-to-image on consumer GPUs.",
    features: {},
    huggingface: "black-forest-labs/FLUX.2-klein-4B",
    popularity: 83,
  },
  {
    id: "z-image-turbo",
    name: "Z-Image Turbo",
    org: "Alibaba",
    family: "Qwen",
    paramsB: 6,
    architecture: "dense",
    contextK: 4,
    license: "Apache 2.0",
    commercial: true,
    released: "2025-11",
    tasks: ["image"],
    description: "8-step distilled image model — photorealism and bilingual text on 16GB cards.",
    features: {},
    popularity: 74,
  },
  {
    id: "llava-13b",
    name: "LLaVA 1.6 13B",
    org: "LLaVA",
    family: "LLaVA",
    paramsB: 13.4,
    architecture: "dense",
    contextK: 4,
    license: "Apache 2.0",
    commercial: true,
    released: "2024-03",
    tasks: ["vision", "chat"],
    description: "Classic local vision-language model. Screenshots, diagrams, OCR-ish chat.",
    features: { vision: true },
    ollama: "llava:13b",
    huggingface: "liuhaotian/llava-v1.6-vicuna-13b",
    popularity: 72,
  },
];

export const MODEL_BY_ID = Object.fromEntries(MODELS.map((m) => [m.id, m]));

export const PROVIDERS = [...new Set(MODELS.map((m) => m.org))].sort();
export const LICENSES = [...new Set(MODELS.map((m) => m.license))].sort();
